---
- name: Join to master node
  hosts: workers
  become: yes
  remote_user: ubuntu

  tasks:
  - name: Join
    ansible.builtin.shell: kubeadm join 10.2.3.31:6443 --гит ругается \
        --гит ругается

